baseURL = 'https://www.progressiverealitytechnology.com/'
languageCode = 'en-us'
title = 'Progressive Reality Technology'
theme = 'tella'
enableRobotsTXT = true

[params]

  showBlog = true
  mainSections = ['blog','slides']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Progressive Reality Technology"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Progressive Reality Technology, a service"
    meta_og_title = "Progressive Reality Technology"
    meta_og_type = "website"
    meta_og_url = "https://www.progressiverealitytechnology.com"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Great technology, much awesome"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2